run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 180
  goimports:
    local-prefixes: github.com/didww/didww-api-3-go-sdk
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1003

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - goconst
        - gocritic
        - unparam
        - dogsled
    - path: testhelper_test\.go
      linters:
        - gochecknoinits
        - unused
  exclude-use-default: false
  exclude:
    - "missing comment on exported"
    - 'func name will be used as test\.Test.* by other packages, and that stutters; consider calling this'
    - "possible misuse of unsafe.Pointer"
    - "ineffective break statement. Did you mean to break out of the outer loop"
